name: Workflow using the k6 run action
on:
  push:

jobs:
  protocol:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Grafana k6
      uses: grafana/setup-k6-action@v0.0.1
      with:
        k6-version: '0.49.0'
    - name: Run k6 tests
      uses: ./
      with:
        path: |
          ./dev/protocol*.js
        flags: --vus 10 --duration 20s
        parallel: true
        fail-fast: false