name: Workflow using the k6 run action
on:
  push:

jobs:
  protocol:
    runs-on: ubuntu-latest
    env:
      K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      K6_CLOUD_PROJECT_ID:  ${{ secrets.K6_CLOUD_PROJECT_ID }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Grafana k6
      uses: grafana/setup-k6-action@v0.0.1
      with:
        k6-version: '0.49.0'
    - uses: ./
      continue-on-error: true
      with:
        path: |
          ./dev/protocol*.js
        flags: --vus 10 --duration 5m
        parallel: false